# .github/workflows/build.yml
name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-pc-windows-gnu]
    steps:
      - uses: actions/checkout@master
      - name: Compile
        id: compile
        uses: rust-build/rust-build.action@v1.4.5
        with:
          RUSTTARGET: ${{ matrix.target }}
          EXTRA_FILES: "README.md LICENSE"
          UPLOAD_MODE: none
      - name: Get package name
        id: cargo-get
        uses: nicolaiunrein/cargo-get@master
        with:
          subcommand: package.version
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: rustrenamer-${{ steps.cargo-get.subcommand }}-${{env.NOW}}-bundled-win-x64
          path: |
            ${{ steps.compile.outputs.BUILT_ARCHIVE }}
            ${{ steps.compile.outputs.BUILT_CHECKSUM }}
